
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 22 17:59:11 CET 2012
//----------------------------------------------------

package pyGrammar;

/** CUP generated interface containing symbol constants. */
public interface PythonSym {
  /* terminals */
  public static final int AT = 65;
  public static final int AS = 3;
  public static final int ANDEQ = 71;
  public static final int FROM = 17;
  public static final int LCURLY = 56;
  public static final int HEX = 78;
  public static final int NEWLINE = 83;
  public static final int RAISE = 28;
  public static final int PLUSEQ = 66;
  public static final int SEMI = 51;
  public static final int LAMBDA = 23;
  public static final int TRIDOT = 35;
  public static final int NAME = 87;
  public static final int PASS = 26;
  public static final int INDENT = 85;
  public static final int EXPEQ = 73;
  public static final int RBRACK = 55;
  public static final int COMMA = 50;
  public static final int DEDENT = 86;
  public static final int OCT = 79;
  public static final int ELIF = 11;
  public static final int RPAREN = 59;
  public static final int LBRACK = 54;
  public static final int LPAREN = 58;
  public static final int DEL = 10;
  public static final int MAIEQ = 47;
  public static final int YIELD = 34;
  public static final int NOT = 24;
  public static final int TILDE = 60;
  public static final int DEF = 9;
  public static final int FLOAT = 81;
  public static final int MINEQ = 45;
  public static final int EQ = 48;
  public static final int MULTMULT = 84;
  public static final int MOD = 41;
  public static final int CLASS = 6;
  public static final int EXCEPT = 13;
  public static final int PIPE = 62;
  public static final int ECOM = 61;
  public static final int PLUS = 37;
  public static final int DIVIDE = 40;
  public static final int EXEC = 14;
  public static final int WHILE = 31;
  public static final int DECIMAL = 76;
  public static final int ASSIGN = 52;
  public static final int LONGINT = 77;
  public static final int FOR = 16;
  public static final int EXPON = 42;
  public static final int RETURN = 29;
  public static final int MULT = 39;
  public static final int ELSE = 12;
  public static final int TRY = 30;
  public static final int BREAK = 5;
  public static final int DOT = 43;
  public static final int MAIOR = 46;
  public static final int EOF = 0;
  public static final int BIN = 80;
  public static final int PRINT = 27;
  public static final int MULTEQ = 68;
  public static final int MINOR = 44;
  public static final int IMPORT = 20;
  public static final int IS = 22;
  public static final int MINUS = 38;
  public static final int DIVDIV = 36;
  public static final int IN = 21;
  public static final int OR = 25;
  public static final int error = 1;
  public static final int LSEQ = 75;
  public static final int DIVEQ = 69;
  public static final int FINALLY = 15;
  public static final int WHITESPACE = 8;
  public static final int CONTINUE = 7;
  public static final int IF = 19;
  public static final int MODEQ = 70;
  public static final int COLON = 53;
  public static final int ASSERT = 4;
  public static final int OREQ = 72;
  public static final int GLOBAL = 18;
  public static final int STRING = 88;
  public static final int RSHIFT = 64;
  public static final int RANGE = 33;
  public static final int RSEQ = 74;
  public static final int IMAGNUM = 82;
  public static final int NEQ = 49;
  public static final int AND = 2;
  public static final int LSHIFT = 63;
  public static final int WITH = 32;
  public static final int RCURLY = 57;
  public static final int MINUSEQ = 67;
}

