
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 16 17:26:24 CET 2011
//----------------------------------------------------

package pyGrammar;

/** CUP generated interface containing symbol constants. */
public interface PythonSym {
  /* terminals */
  public static final int EXCEPT = 12;
  public static final int WITH = 31;
  public static final int OCT = 37;
  public static final int YIELD = 32;
  public static final int CONTINUE = 7;
  public static final int HEX = 36;
  public static final int FOR = 15;
  public static final int ASSERT = 4;
  public static final int NOT = 23;
  public static final int IS = 21;
  public static final int AND = 2;
  public static final int PASS = 25;
  public static final int IN = 20;
  public static final int OR = 24;
  public static final int CLASS = 6;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int DECIMAL = 34;
  public static final int RETURN = 28;
  public static final int LAMBDA = 22;
  public static final int error = 1;
  public static final int NEWLINE = 42;
  public static final int TRY = 29;
  public static final int GLOBAL = 17;
  public static final int BREAK = 5;
  public static final int FINALLY = 14;
  public static final int NAME = 41;
  public static final int FROM = 16;
  public static final int IMPORT = 19;
  public static final int IMAGNUM = 40;
  public static final int BIN = 38;
  public static final int ELSE = 11;
  public static final int WHILE = 30;
  public static final int FLOAT = 39;
  public static final int DEL = 9;
  public static final int STRING = 33;
  public static final int DEF = 8;
  public static final int AS = 3;
  public static final int EXEC = 13;
  public static final int LONGINT = 35;
  public static final int ELIF = 10;
  public static final int PRINT = 26;
  public static final int RAISE = 27;
}

