/* The following code was generated by JFlex 1.4.3 on 16/12/11 16.07 */


package pyGrammar;

import java_cup.runtime.*;
import java.io.IOException;

import pyGrammar.PythonSym;
import static pyGrammar.PythonSym.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/12/11 16.07 from the specification file
 * <tt>F:/Documenti/workspaceANTLR/py2lua/src/pyGrammar/Python.lex</tt>
 */
public final class PythonLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\2\0\1\1\22\0\1\3\1\0\1\17\1\6"+
    "\3\0\1\16\10\0\1\5\1\30\6\25\2\23\7\0\1\27\1\15"+
    "\4\27\5\21\1\22\2\21\1\24\2\21\1\12\2\21\1\13\2\21"+
    "\1\26\2\21\1\0\1\20\2\0\1\4\1\0\1\31\1\14\1\40"+
    "\1\33\1\35\1\44\1\51\1\53\1\43\1\21\1\37\1\41\1\50"+
    "\1\32\1\42\1\46\1\21\1\10\1\34\1\36\1\11\1\21\1\52"+
    "\1\45\1\47\1\21\1\0\1\7\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\1\5\4\3\2\0"+
    "\1\4\16\3\1\6\1\0\1\7\2\0\3\3\1\0"+
    "\1\10\2\0\1\10\1\0\1\3\1\11\10\3\1\12"+
    "\1\13\1\14\1\15\12\3\1\16\1\17\3\3\1\10"+
    "\1\0\2\10\1\20\1\3\1\21\1\22\1\23\4\3"+
    "\1\24\5\3\1\25\12\3\5\0\1\3\1\26\1\27"+
    "\1\30\5\3\1\31\2\3\1\32\2\3\1\33\1\3"+
    "\1\34\1\3\1\35\3\0\2\3\1\36\4\3\1\37"+
    "\1\40\1\3\1\41\1\42\1\10\1\0\1\43\1\44"+
    "\1\3\1\45\1\46\1\3\1\47\1\10\1\3\1\50"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\130\0\204\0\260\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\130\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc"+
    "\0\u07e8\0\u0814\0\u0840\0\u086c\0\204\0\204\0\204\0\204"+
    "\0\u0898\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc"+
    "\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\130"+
    "\0\u0b2c\0\u065c\0\u0b58\0\204\0\u0b84\0\204\0\204\0\204"+
    "\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34\0\204\0\u0c60\0\u0c8c\0\u0cb8"+
    "\0\u0ce4\0\u0d10\0\204\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u0dec"+
    "\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8\0\u0ef4\0\u0f20\0\u0b58"+
    "\0\u0f4c\0\u0f78\0\u0fa4\0\204\0\204\0\204\0\u0fd0\0\u0ffc"+
    "\0\u1028\0\u1054\0\u1080\0\204\0\u10ac\0\u10d8\0\204\0\u1104"+
    "\0\u1130\0\204\0\u115c\0\204\0\u1188\0\204\0\u11b4\0\u11e0"+
    "\0\u120c\0\u1238\0\u1264\0\204\0\u1290\0\u12bc\0\u12e8\0\u1314"+
    "\0\204\0\204\0\u1340\0\204\0\204\0\u11b4\0\u136c\0\204"+
    "\0\204\0\u1398\0\204\0\204\0\u13c4\0\204\0\u136c\0\u13f0"+
    "\0\204\0\204";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\0"+
    "\1\10\1\11\1\12\1\11\1\13\1\11\1\14\1\15"+
    "\1\0\2\5\1\16\1\5\1\16\2\5\1\16\1\17"+
    "\1\20\1\21\1\5\1\22\1\23\1\5\1\24\1\25"+
    "\1\26\1\27\1\30\1\5\1\31\1\32\1\5\1\33"+
    "\1\34\1\5\2\0\1\3\131\0\2\5\2\0\6\5"+
    "\3\0\33\5\5\0\1\35\6\0\2\36\4\0\1\37"+
    "\1\0\1\40\1\35\1\41\1\0\1\35\10\0\1\37"+
    "\1\40\2\0\1\41\6\0\1\7\2\0\4\7\1\0"+
    "\44\7\4\0\2\5\2\0\6\5\1\14\1\15\1\0"+
    "\10\5\1\42\3\5\1\43\16\5\4\0\2\5\2\0"+
    "\1\12\1\5\1\12\3\5\1\14\1\15\1\0\33\5"+
    "\4\0\2\5\2\0\6\5\1\14\1\15\1\0\33\5"+
    "\4\0\2\5\2\0\1\44\1\5\1\12\3\5\1\14"+
    "\1\15\1\0\33\5\2\45\1\0\13\45\1\46\1\45"+
    "\1\47\33\45\2\50\1\0\13\50\1\0\1\51\1\52"+
    "\33\50\5\0\1\16\14\0\1\37\1\16\1\0\1\16"+
    "\2\0\1\16\10\0\1\37\16\0\2\5\2\0\6\5"+
    "\3\0\11\5\1\53\1\5\1\54\17\5\4\0\2\5"+
    "\2\0\6\5\3\0\21\5\1\55\11\5\4\0\2\5"+
    "\2\0\6\5\3\0\14\5\1\56\16\5\4\0\2\5"+
    "\2\0\6\5\3\0\20\5\1\57\3\5\1\60\6\5"+
    "\4\0\2\5\2\0\1\61\5\5\3\0\33\5\4\0"+
    "\2\5\2\0\6\5\3\0\20\5\1\62\1\63\11\5"+
    "\4\0\2\5\2\0\6\5\3\0\10\5\1\64\22\5"+
    "\4\0\2\5\2\0\1\65\5\5\3\0\33\5\4\0"+
    "\2\5\2\0\6\5\3\0\11\5\1\66\1\5\1\67"+
    "\7\5\1\70\3\5\1\71\3\5\4\0\2\5\2\0"+
    "\1\72\5\5\3\0\21\5\1\73\1\74\10\5\4\0"+
    "\2\5\2\0\1\75\5\5\3\0\10\5\1\76\22\5"+
    "\4\0\2\5\2\0\6\5\3\0\22\5\1\77\10\5"+
    "\4\0\2\5\2\0\6\5\3\0\20\5\1\100\12\5"+
    "\4\0\2\5\2\0\6\5\3\0\22\5\1\101\7\5"+
    "\1\102\5\0\1\35\14\0\1\37\2\0\1\35\2\0"+
    "\1\35\10\0\1\37\17\0\1\103\22\0\1\103\30\0"+
    "\1\35\17\0\1\35\2\0\1\35\30\0\1\104\6\0"+
    "\2\104\5\0\1\104\1\0\1\104\1\0\3\104\1\0"+
    "\1\104\1\0\1\104\2\0\1\104\3\0\1\104\13\0"+
    "\2\5\2\0\6\5\3\0\22\5\1\105\10\5\4\0"+
    "\2\5\2\0\6\5\3\0\15\5\1\106\15\5\4\0"+
    "\2\5\2\0\6\5\1\14\1\15\1\0\14\5\1\107"+
    "\16\5\2\45\1\0\13\45\1\110\1\45\1\47\33\45"+
    "\16\0\1\111\42\0\1\45\2\0\6\45\3\0\33\45"+
    "\2\50\1\0\13\50\1\0\1\112\1\52\35\50\1\0"+
    "\13\50\1\0\1\113\1\52\33\50\5\0\1\50\2\0"+
    "\6\50\3\0\33\50\4\0\2\5\2\0\6\5\3\0"+
    "\12\5\1\114\20\5\4\0\2\5\2\0\6\5\3\0"+
    "\13\5\1\115\17\5\4\0\2\5\2\0\6\5\3\0"+
    "\15\5\1\116\15\5\4\0\2\5\2\0\6\5\3\0"+
    "\20\5\1\117\2\5\1\120\7\5\4\0\2\5\2\0"+
    "\6\5\3\0\13\5\1\121\6\5\1\122\10\5\4\0"+
    "\2\5\2\0\6\5\3\0\14\5\1\123\2\5\1\124"+
    "\13\5\4\0\2\5\2\0\6\5\3\0\26\5\1\125"+
    "\4\5\4\0\2\5\2\0\6\5\3\0\10\5\1\126"+
    "\22\5\4\0\2\5\2\0\6\5\3\0\11\5\1\127"+
    "\21\5\4\0\2\5\2\0\6\5\3\0\27\5\1\130"+
    "\3\5\4\0\2\5\2\0\6\5\3\0\25\5\1\131"+
    "\5\5\4\0\2\5\2\0\6\5\3\0\21\5\1\132"+
    "\11\5\4\0\2\5\2\0\1\133\5\5\3\0\33\5"+
    "\4\0\2\5\2\0\6\5\3\0\11\5\1\134\21\5"+
    "\4\0\2\5\2\0\6\5\3\0\22\5\1\135\10\5"+
    "\4\0\2\5\2\0\6\5\3\0\13\5\1\136\17\5"+
    "\4\0\2\5\2\0\6\5\3\0\14\5\1\137\16\5"+
    "\4\0\2\5\2\0\6\5\3\0\21\5\1\140\11\5"+
    "\4\0\2\5\2\0\6\5\3\0\15\5\1\141\15\5"+
    "\4\0\2\5\2\0\6\5\3\0\22\5\1\142\10\5"+
    "\5\0\1\103\14\0\1\37\5\0\1\103\10\0\1\37"+
    "\17\0\1\104\6\0\2\104\4\0\1\37\1\104\1\0"+
    "\1\104\1\0\3\104\1\0\1\104\1\0\1\104\2\0"+
    "\1\104\1\37\2\0\1\104\13\0\2\5\2\0\6\5"+
    "\3\0\13\5\1\143\17\5\4\0\2\5\2\0\1\5"+
    "\1\144\4\5\3\0\33\5\4\0\2\5\2\0\6\5"+
    "\3\0\10\5\1\145\22\5\16\111\1\146\1\111\1\147"+
    "\33\111\2\150\1\151\13\150\1\151\1\113\1\152\33\150"+
    "\4\0\2\5\2\0\6\5\3\0\14\5\1\153\16\5"+
    "\4\0\2\5\2\0\6\5\3\0\14\5\1\154\16\5"+
    "\4\0\2\5\2\0\6\5\3\0\23\5\1\155\7\5"+
    "\4\0\2\5\2\0\6\5\3\0\17\5\1\156\13\5"+
    "\4\0\2\5\2\0\6\5\3\0\14\5\1\157\16\5"+
    "\4\0\2\5\2\0\6\5\3\0\13\5\1\160\17\5"+
    "\4\0\2\5\2\0\6\5\3\0\15\5\1\161\15\5"+
    "\4\0\2\5\2\0\4\5\1\162\1\5\3\0\33\5"+
    "\4\0\2\5\2\0\6\5\3\0\21\5\1\163\11\5"+
    "\4\0\2\5\2\0\6\5\3\0\27\5\1\164\3\5"+
    "\4\0\2\5\2\0\6\5\3\0\10\5\1\165\22\5"+
    "\4\0\2\5\2\0\6\5\3\0\11\5\1\166\21\5"+
    "\4\0\2\5\2\0\6\5\3\0\13\5\1\167\17\5"+
    "\4\0\2\5\2\0\6\5\3\0\20\5\1\170\12\5"+
    "\4\0\2\5\2\0\4\5\1\171\1\5\3\0\33\5"+
    "\4\0\2\5\2\0\6\5\3\0\32\5\1\172\4\0"+
    "\2\5\2\0\6\5\3\0\20\5\1\173\12\5\4\0"+
    "\2\5\2\0\6\5\3\0\14\5\1\174\16\5\4\0"+
    "\2\5\2\0\1\175\5\5\3\0\33\5\4\0\2\5"+
    "\2\0\6\5\3\0\16\5\1\176\14\5\16\111\1\177"+
    "\1\111\1\147\33\111\5\0\1\111\2\0\6\111\3\0"+
    "\33\111\17\151\1\200\1\201\33\151\5\0\1\150\2\0"+
    "\6\150\3\0\33\150\4\0\2\5\2\0\1\202\5\5"+
    "\3\0\33\5\4\0\2\5\2\0\6\5\3\0\25\5"+
    "\1\203\5\5\4\0\2\5\2\0\6\5\3\0\13\5"+
    "\1\204\17\5\4\0\2\5\2\0\6\5\3\0\22\5"+
    "\1\205\10\5\4\0\2\5\2\0\6\5\3\0\12\5"+
    "\1\206\20\5\4\0\2\5\2\0\1\207\5\5\3\0"+
    "\33\5\4\0\2\5\2\0\6\5\3\0\20\5\1\210"+
    "\12\5\4\0\2\5\2\0\6\5\3\0\15\5\1\211"+
    "\15\5\4\0\2\5\2\0\6\5\3\0\12\5\1\212"+
    "\20\5\4\0\2\5\2\0\6\5\3\0\10\5\1\213"+
    "\22\5\4\0\2\5\2\0\6\5\3\0\14\5\1\214"+
    "\16\5\4\0\2\5\2\0\6\5\3\0\11\5\1\215"+
    "\21\5\16\111\1\216\1\111\1\147\33\111\17\151\1\217"+
    "\1\201\33\151\5\0\1\151\2\0\6\151\3\0\33\151"+
    "\4\0\2\5\2\0\6\5\3\0\15\5\1\220\15\5"+
    "\4\0\2\5\2\0\6\5\3\0\15\5\1\221\15\5"+
    "\4\0\2\5\2\0\6\5\3\0\11\5\1\222\21\5"+
    "\4\0\2\5\2\0\6\5\3\0\10\5\1\223\22\5"+
    "\4\0\2\5\2\0\6\5\3\0\15\5\1\224\15\5"+
    "\4\0\2\5\2\0\6\5\3\0\20\5\1\225\12\5"+
    "\4\0\2\5\2\0\6\5\3\0\20\5\1\226\12\5"+
    "\17\151\1\227\1\201\33\151\4\0\2\5\2\0\1\5"+
    "\1\230\4\5\3\0\33\5\4\0\2\5\2\0\6\5"+
    "\3\0\26\5\1\231\4\5\4\0\2\5\2\0\6\5"+
    "\3\0\14\5\1\232\16\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5148];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\7\1\2\0\20\1\1\0\1\11"+
    "\2\0\3\1\1\0\1\1\2\0\1\1\1\0\35\1"+
    "\1\11\1\0\34\1\5\0\24\1\3\0\15\1\1\0"+
    "\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Symbol sym(int type)
	{
		return sym(type, yytext());
	}

	private Symbol sym(int type, Object value)
	{
		return new Symbol(type, yyline, yycolumn, value);
	}

	private void error()
	throws IOException
	{
		throw new IOException("illegal text at line = "+yyline+", column = "+yycolumn+", text = '"+yytext()+"'");
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PythonLex(java.io.Reader in) {
  	// TODO: code that goes to constructor
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public PythonLex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { System.out.println("found decimal"); return sym(DECIMAL);
          }
        case 42: break;
        case 19: 
          { return sym(DEF);
          }
        case 43: break;
        case 30: 
          { return sym(CLASS);
          }
        case 44: break;
        case 34: 
          { return sym(RETURN);
          }
        case 45: break;
        case 23: 
          { return sym(ELIF);
          }
        case 46: break;
        case 39: 
          { return sym(GLOBAL);
          }
        case 47: break;
        case 8: 
          { System.out.println("found string"); return sym(STRING);
          }
        case 48: break;
        case 36: 
          { return sym(EXCEPT);
          }
        case 49: break;
        case 21: 
          { return sym(FOR);
          }
        case 50: break;
        case 38: 
          { return sym(IMPORT);
          }
        case 51: break;
        case 22: 
          { return sym(ELSE);
          }
        case 52: break;
        case 32: 
          { return sym(YIELD);
          }
        case 53: break;
        case 18: 
          { return sym(DEL);
          }
        case 54: break;
        case 26: 
          { return sym(PASS);
          }
        case 55: break;
        case 1: 
          { System.out.println("newline"); return sym(NEWLINE);
          }
        case 56: break;
        case 15: 
          { System.out.println("found hex"); return sym(HEX);
          }
        case 57: break;
        case 13: 
          { return sym(IF);
          }
        case 58: break;
        case 27: 
          { return sym(WITH);
          }
        case 59: break;
        case 24: 
          { return sym(EXEC);
          }
        case 60: break;
        case 10: 
          { return sym(OR);
          }
        case 61: break;
        case 11: 
          { return sym(IN);
          }
        case 62: break;
        case 14: 
          { System.out.println("found bin"); return sym(BIN);
          }
        case 63: break;
        case 33: 
          { return sym(WHILE);
          }
        case 64: break;
        case 29: 
          { return sym(BREAK);
          }
        case 65: break;
        case 25: 
          { return sym(FROM);
          }
        case 66: break;
        case 3: 
          { System.out.println("name"); return sym(NAME);
          }
        case 67: break;
        case 9: 
          { return sym(AS);
          }
        case 68: break;
        case 7: 
          { System.out.println("found longinteger"); return sym(LONGINT);
          }
        case 69: break;
        case 17: 
          { return sym(NOT);
          }
        case 70: break;
        case 16: 
          { return sym(AND);
          }
        case 71: break;
        case 20: 
          { return sym(TRY);
          }
        case 72: break;
        case 31: 
          { return sym(PRINT);
          }
        case 73: break;
        case 28: 
          { return sym(RAISE);
          }
        case 74: break;
        case 41: 
          { return sym(CONTINUE);
          }
        case 75: break;
        case 2: 
          { System.out.println("whitespace");
          }
        case 76: break;
        case 40: 
          { return sym(FINALLY);
          }
        case 77: break;
        case 6: 
          { System.out.println("found oct"); return sym(OCT);
          }
        case 78: break;
        case 37: 
          { return sym(LAMBDA);
          }
        case 79: break;
        case 35: 
          { return sym(ASSERT);
          }
        case 80: break;
        case 12: 
          { return sym(IS);
          }
        case 81: break;
        case 5: 
          { System.out.println("found comment");
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return sym(EOF); 
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
