
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 09 16:36:46 CET 2012
//----------------------------------------------------

package pyGrammar;

/** CUP generated interface containing symbol constants. */
public interface PythonSym {
  /* terminals */
  public static final int AT = 64;
  public static final int AS = 3;
  public static final int ANDEQ = 70;
  public static final int FROM = 16;
  public static final int LCURLY = 55;
  public static final int HEX = 78;
  public static final int NEWLINE = 84;
  public static final int RAISE = 27;
  public static final int PLUSEQ = 65;
  public static final int SEMI = 50;
  public static final int LAMBDA = 22;
  public static final int TRIDOT = 33;
  public static final int NAME = 83;
  public static final int PASS = 25;
  public static final int INDENT = 86;
  public static final int EXPEQ = 72;
  public static final int RBRACK = 54;
  public static final int COMMA = 49;
  public static final int DEDENT = 87;
  public static final int OCT = 79;
  public static final int ELIF = 10;
  public static final int RPAREN = 58;
  public static final int LBRACK = 53;
  public static final int LPAREN = 57;
  public static final int DEL = 9;
  public static final int MAIEQ = 46;
  public static final int YIELD = 32;
  public static final int NOT = 23;
  public static final int TILDE = 59;
  public static final int DEF = 8;
  public static final int FLOAT = 81;
  public static final int MINEQ = 44;
  public static final int EQ = 47;
  public static final int MULTMULT = 85;
  public static final int MOD = 40;
  public static final int CLASS = 6;
  public static final int EXCEPT = 12;
  public static final int PIPE = 61;
  public static final int ECOM = 60;
  public static final int PLUS = 36;
  public static final int DIVIDE = 39;
  public static final int EXEC = 13;
  public static final int WHILE = 30;
  public static final int DECIMAL = 76;
  public static final int ASSIGN = 51;
  public static final int LONGINT = 77;
  public static final int FOR = 15;
  public static final int EXPON = 41;
  public static final int RETURN = 28;
  public static final int MULT = 38;
  public static final int ELSE = 11;
  public static final int TRY = 29;
  public static final int BREAK = 5;
  public static final int DOT = 42;
  public static final int MAIOR = 45;
  public static final int EOF = 0;
  public static final int BIN = 80;
  public static final int PRINT = 26;
  public static final int MULTEQ = 67;
  public static final int MINOR = 43;
  public static final int IMPORT = 19;
  public static final int IS = 21;
  public static final int MINUS = 37;
  public static final int DIVDIV = 34;
  public static final int IN = 20;
  public static final int OR = 24;
  public static final int error = 1;
  public static final int LSEQ = 74;
  public static final int DIVEQ = 68;
  public static final int FINALLY = 14;
  public static final int CONTINUE = 7;
  public static final int IF = 18;
  public static final int MODEQ = 69;
  public static final int COLON = 52;
  public static final int ASSERT = 4;
  public static final int OREQ = 71;
  public static final int GLOBAL = 17;
  public static final int STRING = 75;
  public static final int RSHIFT = 63;
  public static final int RSEQ = 73;
  public static final int IMAGNUM = 82;
  public static final int NEQ = 48;
  public static final int AND = 2;
  public static final int LSHIFT = 62;
  public static final int WITH = 31;
  public static final int RCURLY = 56;
  public static final int XOR = 35;
  public static final int MINUSEQ = 66;
}

