/* The following code was generated by JFlex 1.4.3 on 05/12/11 18.05 */


package luaGrammar;

import java_cup.runtime.*;
import java.io.IOException;

import luaGrammar.LuaGrammarSym;
import static luaGrammar.LuaGrammarSym.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 05/12/11 18.05 from the specification file
 * <tt>F:/Documenti/workspaceANTLR/py2lua/LuaGrammar.lex</tt>
 */
public final class LuaGrammarLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\25\1\21\1\0\1\25\1\24\22\0\1\10\1\0\1\27"+
    "\4\0\1\31\5\0\1\14\1\7\1\0\1\15\3\35\4\35\2\2"+
    "\1\0\1\26\1\0\1\3\3\0\1\20\3\17\1\12\1\20\2\1"+
    "\1\4\2\1\1\11\1\1\1\5\1\11\4\1\1\6\3\1\1\16"+
    "\2\1\1\22\1\30\1\23\1\0\1\1\1\0\1\17\1\33\2\17"+
    "\1\12\1\33\7\1\1\32\3\1\1\32\1\1\1\32\1\34\2\1"+
    "\1\16\2\1\1\0\1\13\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\0\1\2"+
    "\1\4\1\0\1\4\1\5\2\0\2\1\5\0\1\6"+
    "\2\0\1\7\1\1\4\0\1\10\1\0\1\10\1\11"+
    "\6\0\1\10\2\0\1\12\3\0\1\13\1\10\6\0"+
    "\1\12\2\0\1\14\2\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\36\0\74\0\132\0\170\0\226\0\264\0\322"+
    "\0\360\0\132\0\u010e\0\u012c\0\132\0\u014a\0\u0168\0\u0186"+
    "\0\u01a4\0\u01c2\0\u01e0\0\u01fe\0\u021c\0\u023a\0\132\0\u0258"+
    "\0\u0276\0\132\0\u0294\0\u02b2\0\u02d0\0\u02ee\0\u030c\0\u030c"+
    "\0\u032a\0\u0348\0\u01fe\0\u0366\0\u0384\0\u03a2\0\u03c0\0\u03de"+
    "\0\u03fc\0\u02ee\0\u041a\0\u0438\0\132\0\u0456\0\u0474\0\u0492"+
    "\0\132\0\u041a\0\u04b0\0\u04ce\0\u04ec\0\u050a\0\u0528\0\u0546"+
    "\0\u0438\0\u0564\0\u0582\0\132\0\u041a\0\u05a0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\2\6\1\0\1\7"+
    "\1\6\1\2\1\6\1\10\1\11\2\2\1\6\1\12"+
    "\1\13\1\0\1\14\1\12\1\15\1\16\1\0\1\17"+
    "\3\2\1\3\1\0\2\2\1\0\3\2\2\0\3\2"+
    "\1\0\4\2\11\0\4\2\2\0\1\3\12\0\1\3"+
    "\17\0\1\3\37\0\2\2\1\0\1\2\1\20\1\2"+
    "\2\0\1\2\2\21\1\0\4\2\11\0\4\2\1\0"+
    "\2\2\1\0\3\2\2\0\1\2\2\21\1\0\4\2"+
    "\11\0\4\2\12\0\2\22\36\0\1\23\23\0\1\3"+
    "\12\0\1\3\1\24\16\0\1\3\3\0\1\25\16\0"+
    "\1\26\34\0\1\12\14\0\13\16\1\0\5\16\1\0"+
    "\5\16\1\27\1\30\5\16\13\17\1\0\5\17\1\0"+
    "\6\17\1\31\1\32\4\17\1\0\2\2\1\0\2\2"+
    "\1\33\2\0\3\2\1\0\4\2\11\0\4\2\1\0"+
    "\2\2\1\0\3\2\2\0\3\2\1\34\4\2\11\0"+
    "\4\2\4\0\1\35\7\0\1\34\21\0\10\36\1\37"+
    "\2\36\1\37\5\36\1\40\1\41\1\36\1\42\11\36"+
    "\2\0\1\43\7\0\1\43\2\0\1\43\1\0\2\43"+
    "\12\0\1\43\1\0\1\43\3\0\1\25\16\0\1\44"+
    "\13\0\23\26\1\45\12\26\13\0\1\16\1\0\1\16"+
    "\11\0\5\16\1\46\1\16\13\0\1\17\1\0\1\17"+
    "\11\0\5\17\1\47\1\17\1\0\2\2\1\0\3\2"+
    "\1\50\1\0\3\2\1\0\4\2\11\0\4\2\4\0"+
    "\1\35\36\0\1\51\30\0\21\36\1\52\2\36\1\52"+
    "\70\36\1\52\1\53\1\36\1\52\32\36\1\52\14\36"+
    "\23\44\1\54\12\44\23\0\1\55\14\0\1\56\7\0"+
    "\2\56\1\0\1\56\1\0\2\56\12\0\1\56\1\0"+
    "\1\56\2\0\1\57\7\0\2\57\1\0\1\57\1\0"+
    "\2\57\12\0\1\57\1\0\1\57\4\0\1\60\37\0"+
    "\1\61\27\0\21\53\1\62\1\53\1\63\1\62\11\53"+
    "\3\44\1\64\17\44\1\54\12\44\2\0\1\65\7\0"+
    "\2\65\1\0\1\65\1\0\2\65\12\0\1\65\1\0"+
    "\1\65\2\0\1\66\7\0\2\66\1\0\1\66\1\0"+
    "\2\66\12\0\1\66\1\0\1\66\5\0\1\67\30\0"+
    "\21\53\1\62\1\53\1\70\1\62\11\53\3\44\1\64"+
    "\17\44\1\71\12\44\2\0\1\72\7\0\2\72\1\0"+
    "\1\72\1\0\2\72\12\0\1\72\1\0\1\72\2\0"+
    "\1\73\7\0\2\73\1\0\1\73\1\0\2\73\12\0"+
    "\1\73\1\0\1\73\6\0\1\74\27\0\21\53\1\75"+
    "\1\53\1\70\1\76\11\53\2\0\1\16\7\0\2\16"+
    "\1\0\1\16\1\0\2\16\12\0\1\16\1\0\1\16"+
    "\2\0\1\17\7\0\2\17\1\0\1\17\1\0\2\17"+
    "\12\0\1\17\1\0\1\17\21\53\1\75\1\53\1\63"+
    "\1\62\11\53";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1470];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\1\1\11\3\1\1\0\1\1\1\11\1\0"+
    "\1\1\1\11\2\0\2\1\5\0\1\11\2\0\1\11"+
    "\1\1\4\0\1\1\1\0\2\1\6\0\1\1\2\0"+
    "\1\11\3\0\1\11\1\1\6\0\1\1\2\0\1\11"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private Symbol sym(int type)
	{
		return sym(type, yytext());
	}

	private Symbol sym(int type, Object value)
	{
		return new Symbol(type, yyline, yycolumn, value);
	}

	private void error()
	throws IOException
	{
		throw new IOException("illegal text at line = "+yyline+", column = "+yycolumn+", text = '"+yytext()+"'");
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LuaGrammarLex(java.io.Reader in) {
  	// TODO: code that goes to constructor
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LuaGrammarLex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { return sym(ASSIGN);
          }
        case 14: break;
        case 8: 
          { System.out.println("Line comment");
          }
        case 15: break;
        case 1: 
          { return sym(VAR_NAME);
          }
        case 16: break;
        case 6: 
          { System.out.println("Found String");	
				return sym(NORMALSTRING);
          }
        case 17: break;
        case 7: 
          { System.out.println("Found Char String");	
				return sym(CHARSTRING);
          }
        case 18: break;
        case 11: 
          { return sym(EXP);
          }
        case 19: break;
        case 13: 
          { System.out.println("Comment");
          }
        case 20: break;
        case 10: 
          { System.out.println("Found Long String");	
				return sym(LONGSTRING);
          }
        case 21: break;
        case 2: 
          { return sym(INT);
          }
        case 22: break;
        case 12: 
          { return sym(FLOAT);
          }
        case 23: break;
        case 9: 
          { return sym(HEX);
          }
        case 24: break;
        case 4: 
          { 
          }
        case 25: break;
        case 5: 
          { return sym(SEMI);
          }
        case 26: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(luaGrammar.LuaGrammarSym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
