
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 09 12:52:37 CET 2011
//----------------------------------------------------

package luaGrammar;

/** CUP generated interface containing symbol constants. */
public interface LuaGrammarSym {
  /* terminals */
  public static final int LINE_COMMENT = 11;
  public static final int DIVIDE = 21;
  public static final int FUNCTION = 45;
  public static final int MULT = 20;
  public static final int COMMENT = 8;
  public static final int LPAREN = 39;
  public static final int SEMI = 12;
  public static final int REPEAT = 50;
  public static final int INT = 4;
  public static final int MINOR = 25;
  public static final int HEX = 7;
  public static final int FOR = 47;
  public static final int MINUS = 19;
  public static final int RPAREN = 40;
  public static final int NOT = 34;
  public static final int AND = 31;
  public static final int ELSEIF = 53;
  public static final int TRIDOT = 37;
  public static final int NIL = 33;
  public static final int IN = 59;
  public static final int OR = 32;
  public static final int COMMA = 13;
  public static final int EXPON = 23;
  public static final int DOTDOT = 24;
  public static final int UNTIL = 51;
  public static final int PLUS = 18;
  public static final int IF = 52;
  public static final int ASSIGN = 3;
  public static final int EXP = 6;
  public static final int DOT = 14;
  public static final int NORMALSTRING = 15;
  public static final int EOF = 0;
  public static final int MINEQ = 26;
  public static final int RETURN = 57;
  public static final int MAIOR = 27;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int LCURLY = 43;
  public static final int NEWLINE = 10;
  public static final int LONGSTRING = 17;
  public static final int MOD = 22;
  public static final int NEQ = 30;
  public static final int BREAK = 58;
  public static final int EQ = 29;
  public static final int RCURLY = 44;
  public static final int LBRACK = 41;
  public static final int ELSE = 55;
  public static final int SHARP = 38;
  public static final int WS = 9;
  public static final int RBRACK = 42;
  public static final int CHARSTRING = 16;
  public static final int WHILE = 46;
  public static final int MAIEQ = 28;
  public static final int FLOAT = 5;
  public static final int THEN = 54;
  public static final int END = 49;
  public static final int VAR_NAME = 2;
  public static final int LOCAL = 56;
  public static final int FALSE = 35;
  public static final int DO = 48;
}

