
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 05 17:16:46 CET 2011
//----------------------------------------------------

package luaGrammar;

/** CUP generated interface containing symbol constants. */
public interface LuaGrammarSym {
  /* terminals */
  public static final int LINE_COMMENT = 11;
  public static final int INT = 4;
  public static final int WS = 9;
  public static final int NORMALSTRING = 13;
  public static final int LONGSTRING = 15;
  public static final int SEMI = 12;
  public static final int EOF = 0;
  public static final int VAR_NAME = 2;
  public static final int ASSIGN = 3;
  public static final int error = 1;
  public static final int HEX = 7;
  public static final int NEWLINE = 10;
  public static final int COMMENT = 8;
  public static final int EXP = 6;
  public static final int CHARSTRING = 14;
  public static final int FLOAT = 5;
}

