
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 13 10:08:22 CET 2012
//----------------------------------------------------

package pyGrammar;

/** CUP generated interface containing symbol constants. */
public interface PythonSym {
  /* terminals */
  public static final int AT = 69;
  public static final int AS = 3;
  public static final int ANDEQ = 75;
  public static final int FROM = 17;
  public static final int LCURLY = 60;
  public static final int HEX = 82;
  public static final int NEWLINE = 30;
  public static final int RAISE = 35;
  public static final int PLUSEQ = 70;
  public static final int SEMI = 55;
  public static final int LAMBDA = 23;
  public static final int TRIDOT = 28;
  public static final int NAME = 87;
  public static final int PASS = 26;
  public static final int EXPEQ = 77;
  public static final int INDENT = 32;
  public static final int RBRACK = 59;
  public static final int COMMA = 54;
  public static final int DEDENT = 33;
  public static final int OCT = 83;
  public static final int ELIF = 10;
  public static final int RPAREN = 63;
  public static final int LBRACK = 58;
  public static final int LPAREN = 62;
  public static final int DEL = 9;
  public static final int MAIEQ = 51;
  public static final int YIELD = 27;
  public static final int NOT = 24;
  public static final int TILDE = 64;
  public static final int DEF = 8;
  public static final int FLOAT = 85;
  public static final int MINEQ = 49;
  public static final int EQ = 52;
  public static final int MULTMULT = 31;
  public static final int MOD = 45;
  public static final int CLASS = 6;
  public static final int EXCEPT = 12;
  public static final int PIPE = 66;
  public static final int ECOM = 65;
  public static final int PLUS = 41;
  public static final int DIVIDE = 44;
  public static final int EXEC = 13;
  public static final int WHILE = 38;
  public static final int DECIMAL = 80;
  public static final int ASSIGN = 56;
  public static final int LONGINT = 81;
  public static final int FOR = 16;
  public static final int EXPON = 46;
  public static final int RETURN = 36;
  public static final int MULT = 43;
  public static final int ELSE = 11;
  public static final int TRY = 37;
  public static final int BREAK = 5;
  public static final int DOT = 47;
  public static final int MAIOR = 50;
  public static final int EOF = 0;
  public static final int COMMENT = 14;
  public static final int BIN = 84;
  public static final int PRINT = 34;
  public static final int MULTEQ = 72;
  public static final int MINOR = 48;
  public static final int IMPORT = 20;
  public static final int IS = 22;
  public static final int MINUS = 42;
  public static final int DIVDIV = 29;
  public static final int IN = 21;
  public static final int OR = 25;
  public static final int error = 1;
  public static final int LSEQ = 79;
  public static final int DIVEQ = 73;
  public static final int FINALLY = 15;
  public static final int CONTINUE = 7;
  public static final int IF = 19;
  public static final int MODEQ = 74;
  public static final int COLON = 57;
  public static final int ASSERT = 4;
  public static final int OREQ = 76;
  public static final int GLOBAL = 18;
  public static final int STRING = 88;
  public static final int RSHIFT = 68;
  public static final int RANGE = 40;
  public static final int RSEQ = 78;
  public static final int IMAGNUM = 86;
  public static final int NEQ = 53;
  public static final int AND = 2;
  public static final int LSHIFT = 67;
  public static final int WITH = 39;
  public static final int RCURLY = 61;
  public static final int MINUSEQ = 71;
}

