
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 10 16:16:31 CET 2011
//----------------------------------------------------

package pyGrammar;

/** CUP generated interface containing symbol constants. */
public interface PythonSym {
  /* terminals */
  public static final int error = 1;
  public static final int NAME = 3;
  public static final int EOF = 0;
  public static final int NEWLINE = 2;
}

